#!/usr/bin/ruby 
#    Kameleon: a tool to build virtual machines or livecd images
#    Copyright (C) 2009-2010 LIG <http://lig.imag.fr/>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

###############
### loading ###
###############
# required for parsing config files
require 'yaml'

# required for making directories
require 'fileutils'

# required for command parsing
require 'optparse'

# require for injecting configuration
require 'erb'

# required for opening bash session in the background
original_verbose,$VERBOSE = $VERBOSE, nil
begin
 require 'session'
rescue LoadError => e
 warn "The \"session\" module is not found. You need to install it."
 warn "To install session as a debian package (since wheezy), type 'apt-get install ruby-session'."
 warn "To install session as a rubygem, type 'gem install session'."
 begin
   Gem.ruby_version
 rescue
   warn "\nFurthermore, if you plan to use the \"session\" module with rubygems,"
   warn "you maybe have to enable rubygems, by setting RUBYOPT=-rubygems"
   warn "or starting ruby with the -rubygems option."
   exit 1
 end
 exit 1
end
$VERBOSE = original_verbose

# required by exec_shell() function
require 'tempfile'

# required for debugging
require 'pp'

# History file
$histfile="#{ENV['HOME']}/.kameleon_history"
$history=[]

# Cleaning script
$clean_script=`mktemp`
$clean_script.strip!

############################
### function definitions ###
############################

### Hash that keeps elements in the insertion order -- it's more
### convenient for storing macrostep->microstep->comand structure
class OrderedHash < Hash
  def initialize
    @key_list = []
    super
  end
  def []=(key, value)
    if has_key?(key)
      super(key, value)
    else
      @key_list.push(key)
      super(key, value)
    end
  end

  def by_index(index)
    self[@key_list[index]]
  end

  def each
    @key_list.each do |key|
      yield( [key, self[key]] )
    end
  end

  def delete(key)
    @key_list = @key_list.delete_if { |x| x == key }
    super(key)
  end
end

### helper functions for output colorizing
def colorize(text, color_code)
  "#{color_code}#{text}\e[0m"
end

def red(text); colorize(text, "\e[31m\e[1m"); end
def green(text); colorize(text, "\e[32m\e[1m"); end
def blue(text); colorize(text, "\e[34m\e[1m"); end
def cyan(text); colorize(text, "\e[36m"); end

### verifies if the command has to be cached
$cacheable_cmds=[/.*apt-get .* install .*/,/\.*wget \.*/,/\.*git \.*/,]
## This will be used for caching version control systems that cannot be cached
## using the proxy approach.
## Additionally for putting all the scripts used into the cache.
def cmd_cache?(cmd_value,step)
  return nil if cmd_value.nil?
  open("#{$workdir}/cache_file",'a') do |cache_file|
    $cacheable_cmds.each{ |c_cmd|
      cache_file.puts "#{step}: #{cmd_value}" if cmd_value.match c_cmd
    }
    ### the lines below are to keep track of the scripts used and put them into the cache.
    executable = cmd_value.split(" ")[0]
    ## Fix-me  it's a dirty way of doing it 
    path = `which #{executable}`
    if $?.exitstatus == 0
      final_cmd="file `which #{executable}`"
      output = IO.popen(final_cmd)
      if output.readline["text executable"]
        cache_file.puts "#{step}: #{path.chop}"
        ### Generation of the command used for cache it
        cmd_for_cache = "cp #{path.chop} $$cache_dir/#{step}/data/"
        ### redirecting the scrip in the step file
        new_executable = "$$cache_dir/#{step}/data/#{File.basename(executable)}"
        return cmd_for_cache, executable, new_executable
      end
    end
    
  end
  return nil
end

### function for converting command definitions into bash commands
def cmd_parse(cmd,step)
  if cmd.keys[0]=="check_cmd"
    return "which " + cmd.values[0] + " >/dev/null"
  elsif cmd.keys[0]=="check_cmd_chroot"
    return "chroot " + $chroot + " which " + cmd.values[0]
  elsif cmd.keys[0]=="depens"
    return "echo \"OK\""
  elsif cmd.keys[0]=="exec_current"
    return "cd " + $current_dir + "; " + cmd.values[0] #cmd_cache?(cmd.values[0],step)
  elsif cmd.keys[0]=="exec_appliance"
    return "cd " + $chroot + "; " + cmd.values[0] #cmd_cache?(cmd.values[0],step)
  elsif cmd.keys[0]=="exec_chroot"
    return "chroot " + $chroot + " " + cmd.values[0] #cmd_cache?(cmd.values[0],step)
  elsif cmd.keys[0]=="append_file"
    return "echo \"" + cmd.values[0][1] + "\" >> " + $chroot + "/" + cmd.values[0][0]
  elsif cmd.keys[0]=="write_file"
    return "echo \"" + cmd.values[0][1] + "\" > " + $chroot + "/" + cmd.values[0][0]
  elsif cmd.keys[0]=="erb_config"
    return "ERB-config,#{cmd.values[0][0]},#{cmd.values[0][1]}"
  elsif cmd.keys[0]=="set_var"
    return "export " + cmd.values[0][0] + "=\"" + cmd.values[0][1] + "\""
  elsif cmd.keys[0]=="breakpoint"
    return "KML-breakpoint " + cmd.values[0]
  elsif cmd.keys[0]=="exec_ctxt" || cmd.keys[0]=="exec_context"
    return context_parse(cmd.values[0])
  elsif cmd.keys[0]=="exec_on_clean"
    return "echo \"" + cmd.values[0] + "\" > " + $clean_script + ".rev; cat " + $clean_script + ">> " + $clean_script + ".rev; mv -f " + $clean_script + ".rev " + $clean_script
  elsif cmd.keys[0]=="on_clean"
    output=[]
    cmd.values.each do |clean_entry|
      clean_entry.each do |entry|
        entry.each do |clean_cmd,val|
          if clean_cmd == "exec_current"
            output << "echo \"" + val + "\" > " + $clean_script + ".rev; cat " + $clean_script + ">> " + $clean_script + ".rev; mv -f " + $clean_script + ".rev " + $clean_script
          elsif clean_cmd == "exec_appliance"
            output << "echo \"" + "cd " + $chroot + "; " + val + "\" > " + $clean_script + ".rev; cat " + $clean_script + ">> " + $clean_script + ".rev; mv -f " + $clean_script + ".rev " + $clean_script
          elsif clean_cmd == "exec_chroot"
            output << "echo \"" + "chroot " + $chroot + " " + val + "\" > " + $clean_script + ".rev; cat " + $clean_script + ">> " + $clean_script + ".rev; mv -f " + $clean_script + ".rev " + $clean_script
          else
            printf("Step %s: no such on_clean command: %s\n", step, clean_cmd)
            exit(9)
          end
        end
      end
    end
    return output.join(';')
  else
    printf("Step %s: no such command %s\n", step, cmd.keys[0])
    exit(9)
  end
end

# Global variables parsing
def var_parse(str, path)
  str.gsub(/\$\$[a-zA-Z0-9\-_]*/) do
    |c|
    if $recipe['global'][c[2,c.length]]
      c=$recipe['global'][c[2,c.length]]
    else
      printf("%s: variable %s not found in [global] array\n", path, c)
      exit(6)
    end
    return $` + c + var_parse($', path)
  end
end

# Context parsing
def context_parse(str)
  str.gsub(/^\w+/) do
    |context|
    unless $recipe['contexts']
      printf("Missing [contexts] array into recipe\n")
      exit(6)
    end
    if $recipe['contexts'][context]
      if $recipe['contexts'][context]['cmd']
        cmd=$recipe['contexts'][context]['cmd']
        args=$'.strip
      else
        printf("cmd not found in [contexts][%s] array\n", context)
        exit(6)
      end
    else
      printf("context %s not found in [contexts] array\n", context)
      exit(6)
    end
    if $recipe['contexts'][context]['escape']
      escape=$recipe['contexts'][context]['escape']
      args=args.gsub(/[#{escape}]/,"\\\\#{escape}")
    end
    cmd=cmd.gsub(/%%/, args)
    return cmd
    
  end
end

### prompt user in case of command execution error (non-zero exit code)
def error_prompt()
  answer = String.new
  $stdout.flush
  answer=$stdin.gets
  $log.stdin_write(answer)
  while (not ["r\n","c\n","a\n","s\n"].include?(answer))
    print red("Press [r] to retry, [c] to continue with execution, [a] to abort execution, [s] to switch to shell: ")
    $stdout.flush
    answer=$stdin.gets
    $log.stdin_write(answer)
  end
  return answer[0,1]
end

### save an history file
def save_history
  open($histfile,'a') do |f|
    $history.each { |h| f.puts h }
  end
  $history = []
end

### starting cache
def start_cache(shell,cache_dir)
  polipo_bin_path=$current_dir+"/redist/bin"
  # Fix me
  ## there is not error handling here, I have to check if the status code of the execution of the polipo binary
  ##shell.execute("mkdir #{cache_dir}",:stdout => $stdout, :stderr => $stderr) if @options[:path_to_cache].nil?
  shell.execute("export http_proxy=http://localhost:8123",:stdout => $stdout, :stderr => $stderr)
  # out,err=shell.execute(" echo \"starting cache \"")
  # puts "Starting the cache"
  # puts out
  if @options[:path_to_cache].nil?
    #shell.execute("#{polipo_bin_path}/polipo diskCacheRoot=\"#{cache_dir}\" idleTime=\"5\" chunkHighMark=\"425165824\" &",:stdout => $stdout, :stderr => $stderr)
    out, err= shell.execute("#{polipo_bin_path}/polipo diskCacheRoot=\"#{cache_dir}\" idleTime=\"5\" chunkHighMark=\"425165824\" &")
    # puts "printing errors if there are "
    # puts err
  else
    shell.execute("#{polipo_bin_path}/polipo diskCacheRoot=\"#{cache_dir}\" idleTime=\"5\" proxyOffline=\"true\"  chunkHighMark=\"425165824\" &",:stdout => $stdout, :stderr => $stderr)
    #shell.execute("#{polipo_bin_path}/polipo diskCacheRoot=\"#{cache_dir}\" idleTime=\"5\" chunkHighMark=\"425165824\" &",:stdout => $stdout, :stderr => $stderr)
  end
  shell.execute("export polipo_pid=$!")
end

### stoping cache
def stop_cache(shell,cache_dir)
  shell.execute("sleep 2")
  shell.execute("kill -9 $polipo_pid",:stdout => $stdout, :stderr => $stderr)
end

## finish up with the cache
def cache_up(list_cmd)
  sleep 1
  puts green("Copying last files to create the cache")
  list_cmd.each{ |cmd|
    system(cmd)
  }
  ### need to change the steps files
end
### ERB interaction
def config_inject(template_name,output_file)
  ## global variables have to be putted like this global['var']
  # global['distrib'] = "debian"
  # global['arch'] = "amd64"
  begin
    global = {}
    global = $recipe['global'] 
    template_path=$kameleon_templatedir+"/"+template_name
    template_file = File.open(template_path, 'r').read
    erb = ERB.new(template_file)
    File.open(output_file,'w+') { |file|
      file.write(erb.result(binding))
    }
    
    return "ERB done, configuration file: #{output_file} generated"
  rescue
    puts "Cleaning the environment"
    clean
  end
end

### orgmode history saving
def save_orgmode(script_step_hash)
  ## org mode file path 
  org_mode_file=$recipe['global']['workdir']+"/building_flow.org" 
  File.open(org_mode_file,'w') do |file|
    script_step_hash.each do |macrostep|
      macrostep_name = macrostep[0]
      file.puts "* #{macrostep_name}"
      macrostep[1].each do |microstep|
        microstep_name = microstep[0]
        file.puts "** #{microstep_name}"
        microstep[1].each do |command|
          file.puts command
        end
      end
    end
  end  
end

### open prompt in the same enviromnent (shell) where the execution takes place
def start_shell(shell,histfile)
  puts green("Starting shell. Enter 'exit' to return to kameleon.")
#  n = 0
  unless File.file?(rcfile="#{ENV['HOME']}/.kameleon_rc")
    open(rcfile,'w') do |f| 
      f.puts "source #{$recipe['global']['workdir_base']}/\$KAMELEON_TIMESTAMP/kameleon_env" 
      f.puts "PS1='\\e[36;1mKAMELEON \\w # \\e[0m'" 
    end
  end
  shell.execute("env |egrep -v '^PWD='|perl -pi -e 's/=/=\"/'|perl -pi -e 's/\$/\"/' >> #{$workdir}/kameleon_env")
  system("cd #{$workdir}; KAMELEON_TIMESTAMP=#{$timestamp} HISTFILE='#{histfile}' bash --rcfile #{rcfile}")
 
 # loop do
 #   print cyan("#{ n }:SHELL> ")
 #   command = $stdin.gets
 #   $log.stdin_"write(command)
 #   #command = Readline.readline(cyan("#{ n }:SHELL> "), true) 
 #   if command =~ /^\s*\!*history\!*\s*$/
 #     open('shell.history','w'){|f| f.puts shell.history}
 #     next
 #   end
 #   #return if command =~ /^\s*(?:exit|quit)\s*$/io
 #   return if command =~ /^\s*\\q\s*$/io
 #
 #   shell.execute(command, :stdout => $stdout, :stderr => $stderr)
 #   n += 1
 # end
end

def append_to_env_file(line)
  open("#{$workdir}/kameleon_env",'a') { |f| f.puts line }
end

### Cleaning function
def clean()
  puts red("Running cleaning script...")
  system("bash " + $clean_script)
  FileUtils.rm($clean_script)
end

### print usage info
def usage()
  puts "Usage: kameleon.rb recipe[.yaml]"
end

######################################
### parsing command line arguments ###
######################################

@options = {
  :include_path => []
}

option_parser = OptionParser.new do |opts|
  opts.banner = <<BANNER
* Usage
  kameleon [-i data_path] recipe[.yaml]
* Options
BANNER

  opts.on("-i", "--include [PATH]", "Include the given path in the kameleon search path") do |i|
    @options[:include_path].push(File.expand_path(i))
  end

  opts.on("-h","--help", "Show this message.") do
    puts opts
    exit(0)
  end

  opts.on("-o","--output [FILE]",String,"Where to save the image" ) do |o|
     @options[:output_path].puth(File.expand_path(o))
  end

  opts.on("-c","--cache [PATH]","Generate cache for the image created") do |path| 
    @options[:cache] = path || ""
  end

  opts.on("--from_cache [FILE]","Using specific cache to create the image") do |cache_file|
    @options[:path_to_cache] = cache_file
  end
  
  opts.on("--checkpoint [STEP]",String,"Checkpoint after given step") do |step|
    @options[:checkpoint] = step
  end

  opts.on("--chkp_file","Checkpoint from a file") do 
    @options[:checkpoint_file] = true
  end

end

if ARGV.length < 1
  puts option_parser
  exit(1)
end

option_parser.parse!

@options[:recipe] = ARGV[0]

######################
### initialization ###
######################

# define global vars
$current_dir=Dir.pwd
$kameleon_bindir=File.expand_path(File.dirname(__FILE__))
$kameleon_datadir=File.expand_path(File.dirname(__FILE__) + "/../share/kameleon")
$kameleon_templatedir = File.expand_path(File.dirname(__FILE__) + "/config")

version="1.2.8"
required_globals = ["distrib", "workdir_base"]
required_commands = ["chroot", "which", "cat", "echo"]

# check UID (need to be root in order to chacge root)
if Process.uid != 0
  puts "Kameleon: need to be root!"
  exit(3)
end

# open bash session in the background
begin
  bash = Session::Bash.new()
rescue
  print "Failed to open bash session. ", $!, "\n"
  exit(3)
end


# load recipe
path=""
searched_pathes=""
pathes_to_search = []
pathes_to_search += @options[:include_path]
pathes_to_search += @options[:include_path].map { |p|  p + "/recipes" }
pathes_to_search += ["#{$current_dir}", "#{$current_dir}/recipes", "#{$kameleon_datadir}/recipes"]


pathes_to_search.each do |dir|
  if File.file?(search_path1 = dir + "/" + @options[:recipe])
    path=search_path1
    break
  elsif File.file?(search_path2 = dir + "/" + @options[:recipe] + ".yaml")
    path=search_path2
    break
  else
    searched_pathes=searched_pathes + " * " + search_path1 + "[.yaml]" + "\n"
  end
end
if path == ""
  printf("%s: could not find recipe in none of the following files : \n%s", @options[:recipe], searched_pathes)
  exit(2)
end
begin
  puts cyan("->") + green("| Loading " + path)
  $recipe = YAML.load(File.open(path))
rescue
  print "Failed to open recipe file. ", $!, "\n"
  exit(2)
end

# inserting checkpoint if checkpint is enable

if @options[:checkpoint]
  if @options[:checkpoint_file]
    $recipe["steps"].insert($recipe["steps"].index(@options[:checkpoint])+1,'checkpoint_resume')
    while $recipe["steps"].shift!=@options[:checkpoint]
    end    
  else
    puts "step to checkpoint: #{@options[:checkpoint]}"
    $recipe["steps"].insert($recipe["steps"].index(@options[:checkpoint])+1,'checkpoint')
  end
end


# check for required globals in the recipe file
required_globals.each do
  |var|
  if not $recipe['global'][var]
    printf("Recipe misses required variable: %s \n", var)
    exit(4)
  end
end

### Create workdir and chroot directory.
# Dir structure should look like this:
# $workdir_base/<timestamp>/chroot
# Example: /var/tmp/kameleon/2009-07-10-18-55-34/chroot
# We also define two global vars here: $workdir and $chroot
$timestamp=Time.now.strftime("%Y-%m-%d-%H-%M-%S")
start_time=Time.now.to_i
$recipe['global']['recipedir'] = File.basename(path, ".yaml")
$recipe['global']['workdir'] = $workdir = $recipe['global']['workdir_base']+"/"+$timestamp
$recipe['global']['chroot'] = $chroot = $workdir + "/chroot"
$recipe['global']['bindir'] = $current_dir
$recipe['global']['clean'] = $clean_script
begin
  FileUtils.mkdir_p($chroot)
rescue
  print "Failed to create working directory. ", $!, "\n"
  exit(5)
end

# open logfile
class KLogger < File
  def initialize(filename)
    super(filename, 'w')
  end
  def open(filename)
    super(filename, 'w')
  end
  def write(str, stdout="yes")
    if stdout=="yes"
      STDOUT.write(str)
      STDOUT.flush()
    end
    super(str)
    flush()
  end
  def <<(str)
     write(str)
#    STDOUT.<<(str)
#    super(str)
  end
  def stdin_write(str)
     write(str,"no")
  end
end

$log=KLogger.new($workdir + ".log")
$stdout=$log
$stderr=$log

## creating the cache directory if caching is enabled
if @options[:cache]
  cache_dir = @options[:cache].empty? ? $recipe['global']['workdir']+"/cache/" : @options[:cache]+"/cache/"
  FileUtils.mkdir_p(cache_dir)
  ## When creating the cache it is important to save the cache directory as a global variable
  ## to generate actions to cache commands after
  $recipe['global']['cache_dir'] = cache_dir
  ### list of command to be executed so as to complete the cache.
  cache_cmd=[]
end

## if from cache is activated, decompress the tar cache file into the workdir directory
if @options[:path_to_cache] 
  puts green("Untaring cache file into the workdir directory")
  bash.execute("tar -xvf #{@options[:path_to_cache]} -C #{$recipe['global']['workdir']}", :stdout => $stdout, :stderr => $stderr)
  ## to keep the cache direcory in the global variables and have acces form a recipe
  $recipe['global']['cache_dir'] = $recipe['global']['workdir']+"/cache/"
  ## so from the recipe I can do something like:
  ## $$cache/step/archilinux.sh --arch i386    
end
#Readline.output=log

###################
### Preparation ###
###################

# this hash will be used to store pieces of the bash script
script = OrderedHash.new()

# parse recipe, load macrostep files, load microsteps, convert command definitions
# into bash commands. All missing pieces should be detected and reported during
# this phase and before the actual system installation and image building (execution)
$recipe['steps'].each do
  |macrostep|

  # get the name of the step;
  # test if we're dealing with the list of microsteps
  if macrostep.kind_of?(String)
    step = macrostep
  else
    step = macrostep.keys[0]
  end

  # check for a file imported from another distrib
  if step =~ /(.+)\/(.+)/
    step=$2
    dist=$1
  else
    dist=""
  end

  # create a structure that looks something like this:
  # script["oar_init"]["start_appliance_mysql"][0] = \
  # = "chroot /path/to/chroot/dir /etc/init.d/mysql start"
  if script[step].nil?
    script[step] = OrderedHash.new()
  else
    puts "Error: '#{step}' defined twice! Exiting as the first occurence is going to"
    puts "not be executed at all and this is probably not what you want."
    exit(11)
  end

  # check for macrostep file (distro-specific or default)
  path=""
  searched_pathes=""
  pathes_to_search = []
  pathes_to_search += @options[:include_path]
  pathes_to_search += ["#{$current_dir}",  "#{$kameleon_datadir}","#{$kameleon_bindir}"]

  if dist != ""
    pathes_to_search.each do |dir|
      if File.file?(search_path = dir + "/steps/" + dist + "/" + step + ".yaml")
        path=search_path
        break
      else
        searched_pathes=searched_pathes + " * " + search_path + "\n"
      end
    end
  else
    pathes_to_search.each do |dir|
      if File.file?(search_path1 = dir + "/steps/" + $recipe['global']['distrib'] + "/" + step + ".yaml")
        path=search_path1
        break
      elsif File.file?(search_path2 = dir + "/steps/default/" + step + ".yaml")
        path=search_path2
        break
      else
        searched_pathes=searched_pathes + " * " + search_path1 + "\n * " + search_path2 + "\n"
      end
    end
  end
  if path == ""
    printf("%s: macrostep file is missing: \n%s", step, searched_pathes)
    exit(6)
  end

  ### loading steps from cache if is activated
  if @options[:path_to_cache]
    step_name = File.basename(path)
    path = $recipe['global']['workdir']+"/cache/#{step}/"+step_name
    puts green("  | Loading from cache !!!")
  end
  # load macrostep file
  begin
    puts green("  | Loading " + path)
    macrostep_yaml = YAML.load(File.open(path))
    macrostep_yaml_cache =  YAML.load(File.open(path)) if @options[:cache]
  rescue
    print "Failed to open macrostep file. ", $!, "\n"
    exit(7)
  end
  
  ### saving steps if cache is activated
  if @options[:cache] and not @options[:path_to_cache]
    step_name=File.basename(path)
    FileUtils.mkdir(cache_dir+step)
    FileUtils.mkdir(cache_dir+step+"/data/") ## to save scrips used during the creation of the image
    FileUtils.cp(path,cache_dir+"/#{step}/"+step_name)
    # File.open($recipe['global']['workdir']}+"/cache/"+step_name) do |step_file|
    #   YAML.dump(macrostep_yaml,step_file)
    # end
  end
  macrostep_yaml[step].each_index do
    |key|
    microstep=macrostep_yaml[step][key]
    if microstep.keys[0] == "include"
      # load macrostep file
      begin
        macrostep_include_yaml = YAML.load(File.open($current_dir + "/steps/" + microstep.values[0]))
      rescue
        print "Failed to open macrostep file. ", $!, "\n"
        exit(7)
      end
      ind = 1
      macrostep_include_yaml.each do
        |microstep_include|
        macrostep_yaml[step].insert(key+ind, microstep_include)
        ind+=1
      end
      macrostep_yaml[step].delete_at(key)
    end
  end

  # Define the variable stepdir before parsing the yaml file.
  $recipe['global']['stepdir'] = File.basename(path,'.yaml')
 
  # traverse macrosteps->microsteps->commands structure, parse commands;
  # test if we're dealing with the list of microsteps
  if macrostep.kind_of?(String)
    macrostep_yaml[step].each_with_index do
      |microstep,ind_micro|
      script[step][microstep.keys[0]] = Array.new()
      microstep.values[0].each_with_index do
        |command,ind_cmd|
        cmd_string=var_parse(cmd_parse(command,step+"->"+microstep.keys[0]),path)
        script[step][microstep.keys[0]].push(cmd_string)
        ## we test here if we must cache the command executed.
        if @options[:cache]
          action,old_exec,new_exec = cmd_cache?(cmd_string.split(";")[1],step)
          if not action.nil?
            puts "Printing actions #{var_parse(action,path)}"
            cache_cmd.push(var_parse(action,path))
            k = macrostep_yaml_cache[step][ind_micro].values[0][ind_cmd].values[0].split(" ")
            k.shift
#            macrostep_yaml_cache[step][ind_micro].values[0][ind_cmd].values[0][old_exec]=new_exec
            macrostep_yaml_cache[step][ind_micro].values[0][ind_cmd].values[0]="#{new_exec} #{k.join(" ")}"
          end
        end
        cmd_string=cmd_string.gsub(/['()]/,"\\\\\0")
        append_to_env_file("alias #{step}_#{microstep.keys[0]}='#{cmd_string}'")
      end
    end
  else
    if macrostep.values[0].nil?
      puts "Error in recipe: '#{step}' microsteps list is empty!"
      exit 1
    end
    macrostep.values[0].each do
      |microstep|
      script[step][microstep] = Array.new()

      found = nil
      counter = 0
      macrostep_yaml[step].each do
        |microstep_yaml|
        if microstep_yaml.keys[0] == microstep
          found=counter
        end
        counter+=1
      end

      if not found
        printf("Microstep %s required by %s missing in %s.\n", microstep, @options[:recipe], path)
        exit(8)
      end

      macrostep_yaml[step][found].values[0].each do
        |command|
        cmd_string=var_parse(cmd_parse(command,step+"->"+microstep),path)
        script[step][microstep].push(cmd_string)
        cmd_string=cmd_string.gsub(/['()]/,"\\\\\0")
        append_to_env_file("alias #{step}_#{microstep}='#{cmd_string}'")
      end

    end
  end
  ### we have to save the macrostep
  if @options[:cache] 
    step_name=File.basename(path)
    File.open(cache_dir+"/#{step}/"+step_name,'w') do |step_file|
      step_file.write(macrostep_yaml_cache.to_yaml)
    end
  end
end

#################
### Execution ###
#################

puts blue("\n ### ") + green("Welcome to Kameleon " + version) + blue(" ###\n")

trapped=false
trap("INT") {
  if not trapped
    trapped=true
    begin
      bash.close!()
    rescue
    end
    puts red("Interrupted.")
    sleep(1)
    clean()
    puts("Exiting kameleon.")
    save_history
    exit
  end
}

# creating the cache directory
# traverse macrostep->microstep->command structure
script.each do
  |macrostep|
  ## including temporally caching for each step
  macrostep_name=macrostep[0]
  if @options[:cache] then
    cache_dir_step = cache_dir + macrostep_name
    start_cache(bash,cache_dir_step)
  elsif @options[:path_to_cache] 
    cache_dir_step = $recipe['global']['workdir']+"/cache/" + macrostep_name
    start_cache(bash,cache_dir_step)
  end

  macrostep[1].each do
    |microstep|
    microstep_name=microstep[0]
    puts cyan("->") + green("| Executing " + macrostep_name) + cyan("->") + green(microstep_name)
    microstep[1].each do
      |command|
      begin
        next_cmd=0
        while next_cmd!=1
          # check for special command "KML-breakpoint"
          if command[0,14] == "KML-breakpoint"
            puts green("  |-> Breakpoint: " + command[15,command.length])
            # open interactive shell instead of executing a command
            save_history
            start_shell(bash,$histfile)
          elsif command[0,10] == "ERB-config"
            puts green("  |-> Calling ERB config")
            template=command.split(",")[1]
            output_file=command.split(",")[2]
            puts green(" |-> "+ config_inject(template,output_file))
          else
            puts green("  |-> " + command)
            # execute the command in the background bash session, connecting
            # it's stdout and stderr to kameleon's stdout and stderr
            bash.execute(command, :stdout => $stdout, :stderr => $stderr)
            $history << command
          end
          # check exit status, and stop execution on non-zero exit code
          if (bash.exit_status !=0) && (command[0,14] != "KML-breakpoint")
            answer=String.new
            puts red("Error executing command.")
            print red("Press [r] to retry, [c] to continue with execution, [a] to abort execution, [s] to switch to shell: ")
            # offer three options: continue, abort, switch to shell (manually fix the error and then continue)
            while not ["c","r"].include?(answer=error_prompt)
              if answer=="s"
                save_history 
                start_shell(bash,$histfile)
                puts green("Getting back to Kameleon ...")
                print green("Press [r] to retry, [c] to continue with execution, [a] to abort execution, [s] to switch to shell: ")
              elsif answer=="a"
                puts red("Aborting execution ...")
                begin
		  bash.close!()
		rescue
		end
		sleep(1)
		clean()
                puts red("You should clean workdir: " + $workdir)
                exit(10)
              end
            end
            if answer=="c"
              next_cmd=1
            end
          else
            next_cmd=1
          end
        end
      rescue
        printf "%s->%s: Failed to execute command: %s\nException: ", macrostep_name, microstep_name, command
        print $!, "\n"
        exit(3)
      end
    end
  end
  stop_cache(bash,cache_dir_step) if @options[:cache] || @options[:path_to_cache]
end
save_history
## Finishing to generate cache, put it additional files
if @options[:cache]
  cache_up(cache_cmd)
  ## Creating a tar file with the cache contents
  cache_updir=File.dirname(cache_dir) ## the upper dir for cache
  bash.execute("cd #{cache_updir} ; tar -cf cache-#{$timestamp}.tar cache/", :stdout => $stdout, :stderr => $stderr) 
end
begin
  bash.close!()
rescue
end
sleep(1)
clean

### Printing time spend on the whole process
total_time = Time.now.to_i - start_time
puts green("Total time spend on the process: #{total_time} secs")

puts green("Saving everything as org mode format file")
save_orgmode(script)

=begin

=DESCRIPTION

=USAGE

=SEE ALSO

=end
