#!/bin/sh

set -e

modprobe -r ko2iblnd

if [ "$IFACE" != "ib0" ]; then
    exit 0
fi

SHORTNAME=$(hostname -s)

/etc/init.d/openibd restart
/sbin/ifconfig "$IFACE" $(gethostip -d "$SHORTNAME-$IFACE") netmask 255.255.240.0 up


