#!/bin/sh

if [ -n "$new_host_name" ]; then
	if [ -n "$new_domain_name" ]; then
		hostname="${new_host_name}.${new_domain_name}"
	else
		hostname="${new_host_name}"
	fi

	echo "$hostname" > /etc/hostname 2> /dev/null
	hostname "$hostname"
	echo "$hostname" > /etc/mailname 2> /dev/null
fi

